### ISSUE TITLE
Support hapi authStrategies

### ISSUE THREAD

**Issue by zoe-1** [geek/graphi#7]
@geek what do you think about adding support for hapi authStrategies?

My PR #6 adds the feature.

Details:
* authStrategy defaults to false when not set in options.
* authStrategy applies a hapi auth strategy to the
   graphql query route. `./graphql` is the default graphi query route.
* If authStrategy is configured, all queries to the ./graphql route fail
   without a valid token in the header of the request.
* 100% test coverage.
   All tests are performed using 'hapi-auth-bearer-token'.
* New dev dependency 'hapi-auth-bearer-token'.
* New feature does not effect previous operations.

**Comment by geek** [comment]
@zoe-1 thanks for the work! This will be released today as part of v3.1.0
